package entity;
// Generated May 15, 2019 12:02:33 PM by Hibernate Tools 4.3.1



/**
 * Berita generated by hbm2java
 */
public class Berita  implements java.io.Serializable {


     private Integer id;
     private String judul;
     private String tanggal;
     private String isi;

    public Berita() {
    }

    public Berita(String judul, String tanggal, String isi) {
       this.judul = judul;
       this.tanggal = tanggal;
       this.isi = isi;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getJudul() {
        return this.judul;
    }
    
    public void setJudul(String judul) {
        this.judul = judul;
    }
    public String getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(String tanggal) {
        this.tanggal = tanggal;
    }
    public String getIsi() {
        return this.isi;
    }
    
    public void setIsi(String isi) {
        this.isi = isi;
    }




}


