package entity;
// Generated May 15, 2019 12:02:33 PM by Hibernate Tools 4.3.1



/**
 * Kdesa generated by hbm2java
 */
public class Kdesa  implements java.io.Serializable {


     private Integer id;
     private String namaDesa;
     private String deskripsiDesa;
     private String visiMisi;
     private String organisasi;
     private String prestasi;
     private String objectWisata;
     private String gambar;

    public Kdesa() {
    }

    public Kdesa(String namaDesa, String deskripsiDesa, String visiMisi, String organisasi, String prestasi, String objectWisata, String gambar) {
       this.namaDesa = namaDesa;
       this.deskripsiDesa = deskripsiDesa;
       this.visiMisi = visiMisi;
       this.organisasi = organisasi;
       this.prestasi = prestasi;
       this.objectWisata = objectWisata;
       this.gambar = gambar;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNamaDesa() {
        return this.namaDesa;
    }
    
    public void setNamaDesa(String namaDesa) {
        this.namaDesa = namaDesa;
    }
    public String getDeskripsiDesa() {
        return this.deskripsiDesa;
    }
    
    public void setDeskripsiDesa(String deskripsiDesa) {
        this.deskripsiDesa = deskripsiDesa;
    }
    public String getVisiMisi() {
        return this.visiMisi;
    }
    
    public void setVisiMisi(String visiMisi) {
        this.visiMisi = visiMisi;
    }
    public String getOrganisasi() {
        return this.organisasi;
    }
    
    public void setOrganisasi(String organisasi) {
        this.organisasi = organisasi;
    }
    public String getPrestasi() {
        return this.prestasi;
    }
    
    public void setPrestasi(String prestasi) {
        this.prestasi = prestasi;
    }
    public String getObjectWisata() {
        return this.objectWisata;
    }
    
    public void setObjectWisata(String objectWisata) {
        this.objectWisata = objectWisata;
    }
    public String getGambar() {
        return this.gambar;
    }
    
    public void setGambar(String gambar) {
        this.gambar = gambar;
    }




}


