package entity;
// Generated May 15, 2019 12:02:33 PM by Hibernate Tools 4.3.1



/**
 * Saran generated by hbm2java
 */
public class Saran  implements java.io.Serializable {


     private Integer id;
     private String namaDesa;
     private String saran;

    public Saran() {
    }

    public Saran(String namaDesa, String saran) {
       this.namaDesa = namaDesa;
       this.saran = saran;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNamaDesa() {
        return this.namaDesa;
    }
    
    public void setNamaDesa(String namaDesa) {
        this.namaDesa = namaDesa;
    }
    public String getSaran() {
        return this.saran;
    }
    
    public void setSaran(String saran) {
        this.saran = saran;
    }




}


